# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-health-events
  description: Terraform module to configure AWS EventBridge Rules and SNS Notifications for AWS Personal Health Dashboard
  homepage: https://cloudposse.com/accelerate
  topics: ""
